title: "Game News & Wiki"
description: "Tin tức game, nhân vật/tướng, vật phẩm – gọn nhẹ, SEO tốt"
url: "https://duylam0290.github.io"
baseurl: "/game-news-wiki"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

search: true

collections:
  characters:
    output: true
    permalink: /characters/:name/
  items:
    output: true
    permalink: /items/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: ""
      type: "characters"
    values:
      layout: single
      author_profile: false
  - scope:
      path: ""
      type: "items"
    values:
      layout: single
      author_profile: false

paginate: 10
paginate_path: "/news/page:num"
permalink: /:categories/:title/

# Tùy chọn: bật Giscus khi bạn có ID sau
comments:
  provider: giscus
  giscus:
    repo: "Duylam0290/game-news-wiki"
    repo_id: ""
    category: "General"
    category_id: ""
    mapping: "pathname"
    reactions_enabled: true
    input_position: "bottom"
    theme: "preferred_color_scheme"
    lang: "vi"
